[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.19.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.44.4"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.7.0"
